### ISSUE TITLE
[Feature Request] Repeat Folders

### ISSUE THREAD

**Issue by NaturallyAsh** [prncc/obsidian-repeat-plugin#1]
Hey there! Great plugin by the way. Would it be possible to set notes in a specific folder to repeat? I would like to set my Inbox folder, which includes my quick notes, to automatically pop up for review as a reminder to sort them to permanent locations in my vault.

**Comment by prncc** [comment]
Hi. Making all notes in a folder would be possible by adding a `repeat: <frequency>` frontmatter field to all the notes in that folder. See this project's README for details about the format. 

I don't intend to support anything like this in the plugin directly. But if you know how to code, you can write a tool to iterate over the notes, add the `repeat: ...` field to their frontmatter, and it should just work once the notes are ingested.
