### ISSUE TITLE
I am fan

### ISSUE THREAD

**Issue by TfTHacker** [prncc/obsidian-repeat-plugin#2]
I love spaced repetition. this is a great idea!

I have been thinking of implementing something for myself. Not just for review, but for traditional "flashcard cram sessions"

Is your spaced repetition based on SM2?

**Comment by prncc** [comment]
Hi TfTHacker,

Thanks for your support. I don't think this plugin is great for cramming - the smallest repeat frequency is one hour. But I think that's good enough for long-term concept reminders.

The algorithm is simple exponential period modification. The algorithm is described in the README (but basically: make the next repeat 0.5x, 1x, 1.5x, or 2x the current period). IIRC SM2 requires storing a difficulty factor in addition to other metadata, and I wanted to keep the metadata fields simple enough to understand and edit by hand. More conceptually, I could never really intuit what clicking an SM2 "remembering difficulty" button would do, and I value that more than cramming efficiency.

There are some apparently nice plugins for SM2-style flashcards though. https://github.com/reuseman/flashcards-obsidian seems to lets you export parts of notes to Anki.

Also thanks for writing [obsidian42-brat](https://github.com/TfTHacker/obsidian42-brat) - really came in handy when I wanted collapsible backlinks
