### ISSUE TITLE
Spaced repetition

### ISSUE THREAD

**Issue by Adam9331** [prncc/obsidian-repeat-plugin#22]
Dear developer,
I so greatful about this extension,but I got a issue with configuration.
I want to do spaced repetiion for example rewiew note 1 day 2 day 7 days 14 day 1 month 2 month etc
Can I do it with one single command in this extension?

**Comment by prncc** [comment]
Hi, you can write 

```
---
repeat: spaced every day
---
```

at the top of your note. Then as you review, the number of days will be updated automatically. Alternatively, you can use the "Repeat this note..." command which is a GUI for customizing repetition. see https://github.com/prncc/obsidian-repeat-plugin#choosing-notes-to-repeat
