### ISSUE TITLE
Dont work!

### ISSUE THREAD

**Issue by sekretneyslysby** [prncc/obsidian-repeat-plugin#24]
![image](https://github.com/prncc/obsidian-repeat-plugin/assets/88547179/6a2da285-d2bb-402b-80e3-8899840f3c7f)
![image](https://github.com/prncc/obsidian-repeat-plugin/assets/88547179/4ef61cd8-162c-49e1-a62c-afc400f48861)
![image](https://github.com/prncc/obsidian-repeat-plugin/assets/88547179/94450d2e-dfed-473c-a85b-af0a7617c810)

w10 ame
Obsidian Portable 1.1.16
(from installable version going same thing)

new clean vault.. only 2 plugins set...
or i doing something wrong or bug? i dont know
just plz help

**Comment by prncc** [comment]
The way to mark a note to repeat is not by adding a tag like you tried there, but by adding some "properties" to the note.

You don't have to do this manually:

1. Open the note you want to repeat
2. Open the command menu and run the "Repeat: Repeat this note..." command. 
3. Select options for how you want the note to repeat, and press "Set Up Repetition"

Alternatively, add a Property called `repeat` set to `spaced every day` and go to the repeat view. 

Hope that helped - some of this info is also in the README which you can find here: github.com/prncc/obsidian-repeat-plugin.

**Comment by sekretneyslysby** [comment]
in first of all. tnx you
ow... actually moving in case I read the README but don't think about the need open and write command... or that interpretation. Are you thinking about applying the open note and just clicking the plugin on the ribbon and opening that menu? it will be very siple and comfortable

**Comment by prncc** [comment]
1-2) Your note isn't due right away. Look at the "Next repeat" field: it shows when the note becomes due. In this case, the first repetition is a day away, in the evening.

3) I know some people use this plugin to learn vocabulary, so it IS possible. You should use spaced, not periodic repetition. Note that the minimum interval is one hour. 

If you want to add repetition to a whole folder, I suggest making a template so that the metadata is automatically added. Something like this:

```
---
repeat: spaced every day
---
```

**Comment by sekretneyslysby** [comment]
Is it possible to repeat files in multiple folders randomly (by shuffling them among themselves)?

**Comment by prncc** [comment]
Yeah, any note from anywhere you mark with `repeat: spaced every day` will become part of your spaced repetition queue. Notes become due independently -- it's all based on the `repeat` and `due_at` frontmatter fields (now called "Properties').

**Comment by sekretneyslysby** [comment]
Sorry, I don’t understand, will they be repeated only one by one? Can we arrange a random one?

**Comment by prncc** [comment]
You review one-by-one. You always only see one: the one that's most overdue. So if you have 

- note A due 10 days ago
- note B due 2 days ago
- note C due 100 days ago

they will show up in the review pane one by one in this order:

1. C
2. A
3. B

If it's a "spaced" and not "periodic" note, then each time you review, you can select how long before it become due again.

**Comment by sekretneyslysby** [comment]
If i understand correctly, on that method need to set a different time for each note and they will each be displayed randomly?
