### ISSUE TITLE
Spaced repetition timing is incorrectly computed

### ISSUE THREAD

**Issue by wei2912** [prncc/obsidian-repeat-plugin#25]
I have a note with the following metadata:

```
repeat: spaced every 96 hours
due_at: 2023-11-02T06:00:00.000+08:00
```

However, in the note review, the following durations are displayed:

![image](https://github.com/prncc/obsidian-repeat-plugin/assets/2070423/46da3812-735a-4092-8ad4-51da73bc2f0e)

Upon clicking "7 days (x2)" (on 2023-11-02), the metadata changes to the following:

```
repeat: spaced every 182 hours
due_at: 2023-11-10T06:00:00.000+08:00
```

Although the due date is correctly updated to 8 days later, the repetition timing is now 182 instead of 192 hours. (The same output is produced if I set the original `due_at` to `2023-11-01T06:00:00.000+08:00`.)

**Comment by prncc** [comment]
Hey, thanks for reporting. This is actually a feature - not a bug :) The idea is that if your review is far into the future, a few hours won't matter and it's better to have predictable review times. I talk about it a little more in the readme here: https://github.com/prncc/obsidian-repeat-plugin#3-morning-or-evening-repetition

**Comment by wei2912** [comment]
Ahh I see, thanks for the clarification!
