### ISSUE TITLE
Spaced repetition unit resets to "hours" upon choosing skip

### ISSUE THREAD

**Issue by wei2912** [prncc/obsidian-repeat-plugin#28]
For e.g., on 17/1/2024 I have a note as follows with repetition set to `spaced every 2 days`:

![image](https://github.com/prncc/obsidian-repeat-plugin/assets/2070423/8031e816-c980-4027-8f32-9665dc6cc76b)

Upon selecting "5 minutes (skip)" when reviewing, the repetition is set to `spaced every 2 hours`:

![image](https://github.com/prncc/obsidian-repeat-plugin/assets/2070423/fdec613a-2ef7-4a23-b292-6ab086c08a61)

This issue does not affect the repetition period if I set the duration to `spaced every 48 hours`, or select another choice (e.g. "2 days (x1)").

**Comment by prncc** [comment]
Thanks for reporting this! Fixed in release 1.6.1: https://github.com/prncc/obsidian-repeat-plugin/releases/tag/1.6.1
