### ISSUE TITLE
[Feature Request] Undo previous review

### ISSUE THREAD

**Issue by wei2912** [prncc/obsidian-repeat-plugin#29]
Currently, upon pressing the duration buttons, there is no easy way to go back to the previous review and undo the changes (besides manually restoring the latest edited file in File recovery).

This could come in the form of a notification with an "Undo" button, or a keyboard shortcut.

**Comment by prncc** [comment]
I want all data about repetition to be inside the note's header and as simple as possible. To support "undo" the plugin would have to significantly complicate its data model -- I don't think it's worth that. 

Perhaps you can rely on git or other version control mechanisms for Obsidian?
