### ISSUE TITLE
Click Repeat Due notes and then freeze with nothing shown in the developer console. 

### ISSUE THREAD

**Issue by yinlokc** [prncc/obsidian-repeat-plugin#30]
Click Repeat Due notes and then freeze with nothing shown in the developer console. Currently, show 2 repeat note due on the status bar.

As titled, any clues how to fix. Many Thanks.

**Comment by yinlokc** [comment]
To supplement, I use another clean valve to test and it is run perfectly. Think there may be some clash with other plugin. any clues to test it out? Thanks.

**Comment by prncc** [comment]
Hi, a few questions:

1) Does the entire of Obsidian freeze?
2) What version of the plugin are you using?
3) What version of Obsidian are you using?
4) What OS are you on?
5) Can you open the repeat view from the command palette (open the command search and look for "review due notes" -- it should show up)?

**Comment by yinlokc** [comment]
Thanks for your reply and I found out the plug-in clashed with is called "Folder Index". Once removed, I can use Repeat Plugin without any problems. However, I just want to provide the details, in case it is helpful to debug.

1. Does the entire of Obsidian freeze? Yes
2. What version of the plugin are you using? I upgrade to the latest version. 
3. What version of Obsidian are you using? v1.5.3
4. What OS are you on? MacOS
5. Can you open the repeat view from the command palette (open the command search and look for "review due notes" -- it should show up)? No, basically I cannot do anything and can just force quit Obsidian.

**Comment by prncc** [comment]
I installed "Folder Index" but couldn't reproduce -- opening repeat view works without problems. I can even review the virtual folder notes that Folder Index adds.

**Comment by prncc** [comment]
Could you paste your settings for folder index. E.g., 

```
cd ~/Obsidian/Vault/.obsidian/plugins/obsidian-folder-index

cat data.json
```

**Comment by yinlokc** [comment]
Thanks for the follow up. I just remove the plugin before and I also cannot reproduce when I installed the plugin just now. Will report when it happen again. Great Thanks.
