### ISSUE TITLE
[Feature Request] Add descriptor (mapped to the button)  in the "Repeat Due Note" page 

### ISSUE THREAD

**Issue by yinlokc** [prncc/obsidian-repeat-plugin#32]
As subject. The purpose is to provide a descriptor for the repetition, instead of just how long you want the note to be reminded again, which you may be difficult to decide at the moment reviewing the note. 

The best case will be able to add the descriptor mapped to individual button. Thanks. 

<img width="588" alt="image" src="https://github.com/prncc/obsidian-repeat-plugin/assets/2225622/cb92cedb-cced-4890-a2a0-f0f38a6be47f">

5mins - Forgot at all and need to Review Immediately
1 days - Can recall, but take time, need more practice 
2 days - fdalkfjaslkfas
3 days - fjkfjlkdsajflaksd
4 days - I don't need to remember this at all. Just ignore

If it is too complicated, may be just can allow tailor text to be put at the Top of the "Repeat Due Note " page.

**Comment by prncc** [comment]
I'm personally not very interested in this. It seems that the labels you're proposing might not be the right ones for other people, and they would mess with the relatively simple styling. 

I wouldn't mind implementing different algorithms where the labels do have some other meaning, but I don't anticipate having the time. So, I'll close this for now.

If you want to remember what each button means for you, you can create a repeat note with `hidden: true` to quiz yourself :)
