### ISSUE TITLE
Local graph goes empty when opening note via link

### ISSUE THREAD

**Issue by herrsilen** [prncc/obsidian-repeat-plugin#36]
Steps to reproduce:

1. Open Repeat window.
2. Have the local graph open and linked to the active window.
3. Click the link icon to open the note in review.

Local Graph then goes blank and a restart is required for it to show the connected nodes again.

![CleanShot 2024-07-28 at 23 14 52@2x](https://github.com/user-attachments/assets/dc379be9-a9c7-4de6-99b1-4b399218a481)

**Comment by prncc** [comment]
Thanks for reporting this. 

The link icon for a note in review looks like:

```
<a class="markdown-embed-link" href="obsidian://open?vault=Vault&amp;file=Anchors%2FTop%20of%20Mind.md">
<svg><!-- omitted --></svg></a>
```

while links from inside the note like

```
<a data-href="Active Learning Rabbit Hole" href="obsidian://open?vault=Vault&amp;file=Active%20Learning%20Rabbit%20Hole" class="internal-link" target="_blank" rel="noopener">Active Learning Rabbit Hole</a>
```

**Comment by prncc** [comment]
Please upgrade to version 1.7.2 to pick up the fix.
