### ISSUE TITLE
[Feature Request] Add metadata entry - review_count 

### ISSUE THREAD

**Issue by RememerableCL** [prncc/obsidian-repeat-plugin#39]
I'd want do more somethings with this useful plugin, like need something metadata to help implement something like Anki or SuperMemo. Would you be up for adding something like this?

**Comment by prncc** [comment]
Hi -- not interested in supporting more complex spaced repetition algorithms. They require tracking additional metadata, which would add a lot of noise to the properties and make the repetition hard to understand. The "selling points" here are that the repetition algorithm is simple and contained in only 2 properties.
